Update build-web.yml

diff --git a/.github/workflows/build-web.yml b/.github/workflows/build-web.yml
--- a/.github/workflows/build-web.yml
+++ b/.github/workflows/build-web.yml
@@ -6,7 +6,7 @@ env:
   TAG_NAME: "nightly"
   VERSION: "1.3.9"
 
-jobs:      
+jobs:
   build-rustdesk-web:
     name: build-rustdesk-web
     runs-on: ubuntu-24.04
@@ -26,48 +26,46 @@ jobs:
           sudo apt-get install -y wget npm
 
       - name: Install flutter
-        uses: subosito/flutter-action@v2.12.0 #https://github.com/subosito/flutter-action/issues/277
+        uses: subosito/flutter-action@v2.12.0
         with:
           channel: "stable"
           flutter-version: ${{ env.FLUTTER_VERSION }}
 
-      # https://rustdesk.com/docs/en/dev/build/web/
-      - name: Build web
+      - name: Create flutter/web/v2 directory
+        run: |
+          mkdir -p flutter/web/v2
+          echo "Directory flutter/web/v2 created."
+
+      - name: Install dependencies and build web
         shell: bash
         run: |
           pushd flutter/web/v2
           npm install yarn -g
           npm install typescript -g
-          npm install protoc -g
-          # Install protoc first, see: https://google.github.io/proto-lens/installing-protoc.html
           npm install ts-proto
-          # Only works with vite <= 2.8, see: https://github.com/vitejs/vite/blob/main/docs/guide/build.md#chunking-strategy
           npm install vite@2.8
           yarn install && yarn build
           popd
 
-          if [ ! -d "flutter/web/v2" ]; then
-            mkdir -p flutter/web/v2
-            echo "Directory flutter/web/v2 created."
-          fi
+      - name: Download and extract web_deps.tar.gz
+        run: |
           pushd flutter/web/v2
-          wget https://github.com/rustdesk/doc.rustdesk.com/releases/download/console/web_deps.tar.gz
+          wget https://github.com/rustdesk/doc.rustdesk.com/releases/download/console/web_deps.tar.gz || { echo "Failed to download web_deps.tar.gz"; exit 1; }
           tar xzf web_deps.tar.gz
           popd
 
+      - name: Build Flutter Web Release
+        run: |
           pushd flutter
           flutter build web --release
           cd build
-          #cp ../web/README.md web
-          # TODO: Remove the following line when the web is almost complete.
-          #echo -e "\n\nThis build is for preview and not full functionality." >> web/README.md
           dir_name="rustdesk-${{ env.VERSION }}-${{ env.RELEASE_NAME }}"
-          mv web "${dir_name}" && tar czf "${dir_name}".tar.gz "${dir_name}"
-          sha256sum "${dir_name}".tar.gz
+          mv web "${dir_name}" && tar czf "${dir_name}.tar.gz" "${dir_name}"
+          sha256sum "${dir_name}.tar.gz"
           popd
 
       - name: Upload APK artifact
         uses: actions/upload-artifact@v4
         with:
-            name: web
-            path: flutter/build/rustdesk-${{ env.VERSION }}-${{ env.RELEASE_NAME }}.tar.gz
+          name: web
+          path: flutter/build/rustdesk-${{ env.VERSION }}-${{ env.RELEASE_NAME }}.tar.gz
